### ISSUE TITLE
Drop down for model selection

### ISSUE THREAD

**Issue by zhuangjun1981** [dougollerenshaw/CodeAIde#29]
This is more like a feature request: it would be nice to have dropdown that allow the user to pick what LLM model to use.

**Comment by dougollerenshaw** [comment]
Thanks @zhuangjun1981 ! I have that same idea in mind. See the second point in my roadmap on the readme:
https://github.com/dougollerenshaw/CodeAIde?tab=readme-ov-file#future-feature-roadmap

I'll to set up a file that tracks which models are available from each company and link the associated API key to that model.

I'd also like to find a way to make basic functionality free so people can try this out without having to immediately sign up for an API key. If you have any thoughts on how to do that, let me know! I'd like to either set a free model as the default or find some way to allow first-time users to send a few responses without charge before needing an API key. I think some APIs do have introductory offers, but I don't know how to set that up so that every new user would automatically get that. Was planning to learn more.
